questions = [
	{"name" : "What county is Indianapolis located in?", "answers" : ["Marion County", "Hendricks County", "Hancock County", "Kosciusko County"], "answer" : "Marion County", "type" : "geo-usa"},
    {"name" : "Which state has the fewest counties?", "answers" : ["Delaware", "Rhode Island", "Vermont", "Connecticut"], "answer" : "Delaware", "type" : "geo-usa"},
    {"name" : "How many counties does Rhode Island have?", "answers" : ["4", "5", "6", "8"], "answer" : "5", "type" : "geo-usa"},
    {"name" : "How many counties does Delaware have?", "answers" : ["2", "3", "4", "6"], "answer" : "3", "type" : "geo-usa"},
    {"name" : "Where is Waterton Lakes National Park?", "answers" : ["Alberta", "Yukon", "British Columbia", "Saskatchewan"], "answer" : "Alberta", "type" : "geo-can"},
    {"name" : "Where is Georgian Bay Islands National Park?", "answers" : ["Ontario", "Northwest Territories", "British Columbia", "Quebec"], "answer" : "Ontario", "type" : "geo-can"},
    {"name" : "What is the only urban national park in Canada?", "answers" : ["Rouge National Park", "Sable Island National Park", "Saguenay National Park", "Elbow River National Park"], "answer" : "Rouge National Park", "type" : "geo-can"},
    {"name" : "What is the largest city in New Brunswick?", "answers" : ["Moncton", "Fredericton", "Dieppe", "Bathurst"], "answer" : "Moncton", "type" : "geo-can"},
    {"name" : "What is the smallest state of Germany?", "answers" : ["Saarland", "Berlin", "Hamburg", "Bremen"], "answer" : "Bremen", "type" : "geo-eur"},
    {"name" : "Where is the largest train station in Europe?", "answers" : ["Russia", "France", "Italy", "Germany"], "answer" : "Germany", "type" : "geo-eur"},
    {"name" : "What is the smallest lake in Europe?", "answers" : ["Lake Ladoga", "Lake Geneva", "Lake Onega", "Lake Saimaa"], "answer" : "Lake Ladoga", "type" : "geo-eur"},
    {"name" : "Are there deserts in Europe?", "answers" : ["True","False"], "answer" : "True", "type" : "geo-eur"},
    {"name" : "Where is the geographic center of North America?", "answers" : ["Saskatchewan", "Alberta", "Manitoba", "Montana"], "answer" : "Saskatchewan", "type" : "geo-can"},
    {"name" : "How many cities in Canada have a population greater than one million?", "answers" : ["6", "5", "7", "4"], "answer" : "6", "type" : "geo-can"},
    {"name" : "What is the tallest mountain peak in Canada?", "answers" : ["Mount Thor", "Mount Logan", "Mount Lucania", "King Peak"], "answer" : "Mount Logan", "type" : "geo-can"},
    {"name" : "Where is the world's longest known cave system?", "answers" : ["Kentucky", "Tennessee", "Minnesota", "West Virginia"], "answer" : "Kentucky", "type" : "geo-usa"},
    {"name" : "What is the oldest monarchy in the world?", "answers" : ["United Kingdom", "Denmark", "Japan", "Norway"], "answer" : "Japan", "type" : "hist"},
    {"name" : "What is the first state of the United States?", "answers" : ["Delaware", "Pennsylvania", "Connecticut", "New Jersey"], "answer" : "Delaware", "type" : "hist-usa"},
    {"name" : "When did Newfoundland and Labrador join Canada?", "answers" : ["1933", "1949", "1941", "1954"], "answer" : "1949", "type" : "hist-can"},
    {"name" : "Who is the only American president to hold a PhD?", "answers" : ["Woodrow Wilson", "George W. Bush", "Rutherford B. Hayes", "Theodore Roosevelt"], "answer" : "Woodrow Wilson", "type" : "hist-usa"},
    {"name" : "Which city is the capital of New Jersey?", "answers" : ["Trenton", "Newark", "Hackensack", "New Brunswick"], "answer" : "Trenton", "type" : "geo-usa"},
    {"name" : "What is the oldest university in the United States?", "answers" : ["Harvard University", "Yale University", "Princeton University ", "The College of William and Mary"], "answer" : "Harvard University", "type" : "hist-usa"},
    {"name" : "What is the oldest university in Canada?", "answers" : ["Université Laval", "University of Toronto", "University of King's College", "McGill University"], "answer" : "Université Laval", "type" : "hist-can"},
    {"name" : "Who is the shortest serving prime minister of Canada?", "answers" : ["John Turner", "Kim Campbell", "Charles Tupper", "Joe Clark"], "answer" : "Charles Tupper", "type" : "hist-can"},
    {"name" : "Who is the longest serving prime minister of Canada?", "answers" : ["Wilfrid Laurier", "John A. McDonald", "Pierre Trudeau", "William Lyon Mackenzie King"], "answer" : "William Lyon Mackenzie King", "type" : "hist-can"},
	{"name" : "Are there rainforests in Europe?", "answers" : ["True","False"], "answer" : "True", "type" : "geo-eur"},
	{"name" : "Who is the shortest serving American president?", "answers" : ["John F. Kennedy", "James Garfield", "William Henry Harrison", "Zachary Taylor"], "answer" : "William Henry Harrison", "type" : "hist-usa"},
	{"name" : "How many American presidents were affiliated with the Whig party?", "answers" : ["4", "3", "2", "5"], "answer" : "4", "type" : "hist-usa"},
	{"name" : "By area, what is the largets borough of New York?", "answers" : ["Brooklyn", "Queens", "Bronx", "Staten Island"], "answer" : "Queens", "type" : "geo-usa"},
]
